package de.frankbeeh.productbacklogtimeline.service.database;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Responsibility:
 * <ul>
 * <li>Creates the not yet existing tables in the DB.
 * </ul>
 */
public class DatabaseService {
    private static final String CREATE_PBI_TABLE = "CREATE TABLE IF NOT EXISTS PBI (ID CHAR(20) NOT NULL, HASH CHAR(40) NOT NULL, TITLE TEXT, DESCRIPTION TEXT, ESTIMATE DOUBLE, STATE TEXT NOT NULL, SPRINT TEXT, RANK TEXT, PLANNED_RELEASE TEXT, CONSTRAINT PK_PBI PRIMARY KEY (ID, HASH))";
    private static final String CREATE_PBL_TABLE = "CREATE TABLE IF NOT EXISTS PBL (PT_ID TIMESTAMP NOT NULL, PBI_ID CHAR(20) NOT NULL, PBI_HASH CHAR(40) NOT NULL, CONSTRAINT PK_PBI FOREIGN KEY (PBI_ID, PBI_HASH) REFERENCES PBI(PBI_ID, PBI_HASH), CONSTRAINT PK_PT FOREIGN KEY (PT_ID) REFERENCES PRODUCT_TIMESTAMP(ID))";
    private static final String CREATE_SPRINT_TABLE = "CREATE TABLE IF NOT EXISTS SPRINT (NAME VARCHAR(100) NOT NULL, START DATE NOT NULL, END DATE NOT NULL, HASH CHAR(40) NOT NULL, CAPACITY_FORECAST DOUBLE, EFFORT_FORECAST DOUBLE, CAPACITY_DONE DOUBLE, EFFORT_DONE DOUBLE, CONSTRAINT PK_SPRINT PRIMARY KEY (END, HASH))";
    private static final String CREATE_VELOCITY_FORECAST_TABLE = "CREATE TABLE IF NOT EXISTS VELOCITY_FORECAST (PT_ID TIMESTAMP NOT NULL, SPRINT_END DATE NOT NULL, SPRINT_HASH CHAR(40) NOT NULL, CONSTRAINT PK_PBI FOREIGN KEY (SPRINT_END, SPRINT_HASH) REFERENCES SPRINT(END, HASH), CONSTRAINT PK_PT FOREIGN KEY (PT_ID) REFERENCES PRODUCT_TIMESTAMP(ID))";
    private static final String CREATE_RELEASE_TABLE = "CREATE TABLE IF NOT EXISTS RELEASE (NAME VARCHAR(100) NOT NULL, CRITERIA VARCHAR(100) NOT NULL, HASH CHAR(40) NOT NULL, CONSTRAINT PK_RELEASE PRIMARY KEY (HASH))";
    private static final String CREATE_RELEASES_TABLE = "CREATE TABLE IF NOT EXISTS RELEASES (PT_ID TIMESTAMP NOT NULL, RELEASE_HASH CHAR(40) NOT NULL, CONSTRAINT PK_RELEASES FOREIGN KEY (RELEASE_HASH) REFERENCES RELEASE(HASH), CONSTRAINT PK_PT FOREIGN KEY (PT_ID) REFERENCES PRODUCT_TIMESTAMP(ID))";
    private static final String CREATE_PRODUCT_TIMESTAMP_TABLE = "CREATE TABLE IF NOT EXISTS PRODUCT_TIMESTAMP (ID TIMESTAMP NOT NULL, NAME VARCHAR(100) NOT NULL, CONSTRAINT PK_PT PRIMARY KEY (ID))";

    private final Connection connection;

    public DatabaseService(Connection connection) {
        this.connection = connection;
    }

    public void createTables() throws ClassNotFoundException, SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate(CREATE_PBI_TABLE);
            statement.executeUpdate(CREATE_PBL_TABLE);
            statement.executeUpdate(CREATE_SPRINT_TABLE);
            statement.executeUpdate(CREATE_VELOCITY_FORECAST_TABLE);
            statement.executeUpdate(CREATE_RELEASE_TABLE);
            statement.executeUpdate(CREATE_RELEASES_TABLE);
            statement.executeUpdate(CREATE_PRODUCT_TIMESTAMP_TABLE);
        }
    }
}
